version: '3'
services: 
   app:
     image: jenkinsci/blueocean
     ports:
      - 8080:8080
      - 50000:50000
     volumes:
      - jenkinsdata:/var/jenkins_home
      - some-docker-certs-client:/certs/client
      - some-docker-certs-ca:/certs/ca
      - lib-sonar:/usr/src
      - sonar-cache:~/.sonar
     networks:
      - jenkins
     environment:
      - DOCKER_HOST=tcp://docker:2376
      - DOCKER_CERT_PATH=/certs/client 
      - DOCKER_TLS_VERIFY=1 
     depends_on:
      - docker
   docker:
     image: docker:dind
     networks:
      - jenkins
     privileged: true
     environment:
      - DOCKER_CERT_PATH=/certs/client 
      - DOCKER_TLS_CERTDIR=/certs
      - DOCKER_TLS_VERIFY=1 
     volumes:
      - some-docker-certs-client:/certs/client
      - some-docker-certs-ca:/certs/ca
      - jenkinsdata:/var/jenkins_home
     

networks:
  jenkins:
    external:
       name: gateway

volumes:
  jenkinsdata:
  some-docker-certs-ca:
  some-docker-certs-client:
  # for cache plugin sonarqube
  lib-sonar:
